groups:
- name: 改签底座质量监控
  mode: alert
  process_mode: all
  id: cidfdkcdGeG9tIxgxdLeLYyFQ==
  enabled: true
  auto_reply_types:
  - 验价
  - 验座
- name: 改签审计报警群
  mode: both
  process_mode: at_me_only
  id: cidSFf31OAsYq2VMu8yxLuNmA==
  enabled: true
- name: 底座机器人
  mode: at_me
  id: cidVgpQHNmH4sjUrSIalDWFOg==
  enabled: false
